### ISSUE TITLE
Replace deprecated packages with alternatives

### ISSUE THREAD

**Issue by kranse** [piotrwitek/typesafe-actions-todo-app#1]
Since [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) is now deprecated, and [react-router-redux](https://github.com/reactjs/react-router-redux) has been for some time, it seems like a good idea to update to [CRA2.1](https://facebook.github.io/create-react-app/docs/adding-typescript) and [connected-react-router](https://github.com/supasate/connected-react-router).

**Comment by piotrwitek** [comment]
Closing as this repo is now moved to: https://codesandbox.io/s/github/piotrwitek/typesafe-actions/tree/master/codesandbox
